import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export type BookingDocumentData = {
	resortName: string;
	resortAddress: string;
	resortEmail: string;
	resortPhone: string;
	propertyName: string;
	guestName: string;
	guestEmail: string;
	guestPhone: string;
	checkIn: string;
	checkOut: string;
	nights: number;
	guests: number;
	subtotal: number;
	discountAmount: number;
	total: number;
	currency: string;
	confirmationCode?: string;
	invoiceNumber?: string;
	receiptNumber?: string;
	paidAt?: number;
	createdAt?: number;
};

function money(amount: number, currency: string) {
	return `${currency} ${amount.toLocaleString()}`;
}

function formatDate(value: number | undefined) {
	return new Intl.DateTimeFormat('en', {
		year: 'numeric',
		month: 'short',
		day: 'numeric'
	}).format(value ? new Date(value) : new Date());
}

async function createDocument(title: string, data: BookingDocumentData) {
	const pdf = await PDFDocument.create();
	const page = pdf.addPage([595.28, 841.89]);
	const regular = await pdf.embedFont(StandardFonts.Helvetica);
	const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
	const navy = rgb(0.09, 0.11, 0.17);
	const muted = rgb(0.38, 0.4, 0.46);
	const gold = rgb(0.78, 0.55, 0.24);
	let y = 780;

	const text = (
		value: string,
		x: number,
		size = 10,
		font = regular,
		color = navy
	) => {
		page.drawText(value, { x, y, size, font, color });
	};

	page.drawText(data.resortName, { x: 48, y, size: 22, font: bold, color: navy });
	page.drawText(title, { x: 420, y: y + 4, size: 18, font: bold, color: gold });
	y -= 26;
	page.drawText(data.resortAddress, { x: 48, y, size: 9, font: regular, color: muted });
	y -= 14;
	page.drawText(`${data.resortEmail} | ${data.resortPhone}`, {
		x: 48,
		y,
		size: 9,
		font: regular,
		color: muted
	});

	y -= 46;
	page.drawRectangle({
		x: 48,
		y: y - 78,
		width: 499,
		height: 92,
		borderColor: rgb(0.86, 0.86, 0.86),
		borderWidth: 1,
		color: rgb(0.98, 0.97, 0.94)
	});
	y -= 18;
	text(`Guest: ${data.guestName}`, 66, 11, bold);
	y -= 18;
	text(`Email: ${data.guestEmail}`, 66, 10, regular, muted);
	y -= 18;
	text(`Phone: ${data.guestPhone}`, 66, 10, regular, muted);
	y -= 18;
	text(`Property: ${data.propertyName}`, 66, 10, regular, muted);

	y -= 48;
	text(`Stay dates: ${data.checkIn} to ${data.checkOut}`, 48, 11, bold);
	y -= 18;
	text(`${data.nights} night${data.nights === 1 ? '' : 's'} · ${data.guests} guest${data.guests === 1 ? '' : 's'}`, 48, 10, regular, muted);

	y -= 40;
	const row = (label: string, value: string, strong = false) => {
		page.drawText(label, {
			x: 48,
			y,
			size: strong ? 12 : 10,
			font: strong ? bold : regular,
			color: strong ? navy : muted
		});
		page.drawText(value, {
			x: 430,
			y,
			size: strong ? 12 : 10,
			font: strong ? bold : regular,
			color: strong ? navy : muted
		});
		y -= strong ? 24 : 20;
	};

	row(`${data.propertyName} x ${data.nights} night${data.nights === 1 ? '' : 's'}`, money(data.subtotal, data.currency));
	row('Direct booking discount', `-${money(data.discountAmount, data.currency)}`);
	page.drawLine({ start: { x: 48, y: y + 6 }, end: { x: 547, y: y + 6 }, thickness: 1, color: rgb(0.86, 0.86, 0.86) });
	row('Total', money(data.total, data.currency), true);

	return { pdf, page, regular, bold, navy, muted, gold, y };
}

export async function buildInvoicePdf(data: BookingDocumentData) {
	const doc = await createDocument('Invoice', data);
	let y = doc.y - 18;
	doc.page.drawText(`Invoice number: ${data.invoiceNumber ?? 'Demo invoice'}`, {
		x: 48,
		y,
		size: 10,
		font: doc.bold,
		color: doc.navy
	});
	y -= 16;
	doc.page.drawText(`Issue date: ${formatDate(data.createdAt)}`, {
		x: 48,
		y,
		size: 10,
		font: doc.regular,
		color: doc.muted
	});
	y -= 34;
	doc.page.drawText('This demo invoice was generated by Seaview Residence for product demonstration only.', {
		x: 48,
		y,
		size: 9,
		font: doc.regular,
		color: doc.muted
	});
	return doc.pdf.save();
}

export async function buildReceiptPdf(data: BookingDocumentData) {
	const doc = await createDocument('Receipt', data);
	let y = doc.y - 18;
	doc.page.drawText(`Receipt number: ${data.receiptNumber ?? 'Demo receipt'}`, {
		x: 48,
		y,
		size: 10,
		font: doc.bold,
		color: doc.navy
	});
	y -= 16;
	doc.page.drawText(`Confirmation code: ${data.confirmationCode ?? 'Demo confirmation'}`, {
		x: 48,
		y,
		size: 10,
		font: doc.regular,
		color: doc.muted
	});
	y -= 16;
	doc.page.drawText(`Paid date: ${formatDate(data.paidAt)}`, {
		x: 48,
		y,
		size: 10,
		font: doc.regular,
		color: doc.muted
	});
	y -= 16;
	doc.page.drawText('Payment method: Demo card ending in 4242', {
		x: 48,
		y,
		size: 10,
		font: doc.regular,
		color: doc.muted
	});
	y -= 34;
	doc.page.drawText('Paid in full. This receipt is for demo purposes and no real card was charged.', {
		x: 48,
		y,
		size: 9,
		font: doc.regular,
		color: doc.muted
	});
	return doc.pdf.save();
}

export function downloadPdf(bytes: Uint8Array, filename: string) {
	const arrayBuffer = new ArrayBuffer(bytes.byteLength);
	new Uint8Array(arrayBuffer).set(bytes);
	const blob = new Blob([arrayBuffer], { type: 'application/pdf' });
	const url = URL.createObjectURL(blob);
	const link = document.createElement('a');
	link.href = url;
	link.download = filename;
	document.body.append(link);
	link.click();
	link.remove();
	URL.revokeObjectURL(url);
}
