import type { FaqRecord, PropertyMediaRecord, PropertyRecord } from "./domain";

const demoTimestamp = "2026-06-21T00:00:00.000Z";
const demoActor = "demo";

export const demoProperties: PropertyRecord[] = [
  {
    id: "demo-riverfront-loft",
    slug: "riverfront-loft",
    title: "Riverfront Loft",
    description: "Bright condo with river views, a work-from-home nook, and quick access to restaurants, trails, and downtown transit.",
    status: "published",
    transactionMode: "rent",
    propertyType: "condo",
    price: "2400",
    currency: "USD",
    deposit: "2400",
    feesText: "Pet fee may apply.",
    bedrooms: "2",
    bathrooms: "2",
    areaSize: "1140",
    areaUnit: "sqft",
    addressDisplay: "201 River Walk",
    city: "Austin",
    district: "Downtown",
    provinceOrState: "Texas",
    country: "United States",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Austin+River+Walk",
    availabilityText: "Available now",
    availableFrom: "2026-07-01",
    amenities: "Parking|Gym|Balcony|In-unit laundry",
    youtubeUrl: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
    floorPlanUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    primaryImageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-garden-townhouse",
    slug: "garden-townhouse",
    title: "Garden Townhouse",
    description: "Three-level townhouse with a small private garden, finished lower level, and a quiet residential setting near commuter rail.",
    status: "published",
    transactionMode: "rent",
    propertyType: "townhouse",
    price: "3150",
    currency: "USD",
    deposit: "3150",
    feesText: "Utilities billed separately.",
    bedrooms: "3",
    bathrooms: "2.5",
    areaSize: "1880",
    areaUnit: "sqft",
    addressDisplay: "44 Maple Terrace",
    city: "Denver",
    district: "Highlands",
    provinceOrState: "Colorado",
    country: "United States",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Denver+Highlands",
    availabilityText: "Available August 15",
    availableFrom: "2026-08-15",
    amenities: "Garden|Garage|Dishwasher|Storage",
    youtubeUrl: "",
    floorPlanUrl: "",
    primaryImageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-sunlit-studio",
    slug: "sunlit-studio",
    title: "Sunlit Studio",
    description: "Efficient studio apartment with oversized windows, a renovated kitchen, and a building lounge for residents.",
    status: "published",
    transactionMode: "rent",
    propertyType: "apartment",
    price: "1550",
    currency: "USD",
    deposit: "1550",
    feesText: "Application and move-in fees may apply.",
    bedrooms: "0",
    bathrooms: "1",
    areaSize: "520",
    areaUnit: "sqft",
    addressDisplay: "730 Lake Street",
    city: "Chicago",
    district: "West Loop",
    provinceOrState: "Illinois",
    country: "United States",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Chicago+West+Loop",
    availabilityText: "Available in 30 days",
    availableFrom: "2026-07-21",
    amenities: "Elevator|Resident lounge|Bike room",
    youtubeUrl: "",
    floorPlanUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    primaryImageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  }
];

export const demoMedia: PropertyMediaRecord[] = [
  {
    id: "demo-media-riverfront-1",
    propertyId: "demo-riverfront-loft",
    type: "photo",
    url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    altText: "Living room in the Riverfront Loft",
    caption: "River-facing living area",
    sortOrder: "1",
    isPrimary: true,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-media-riverfront-2",
    propertyId: "demo-riverfront-loft",
    type: "photo",
    url: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    altText: "Bedroom in the Riverfront Loft",
    caption: "Quiet primary bedroom",
    sortOrder: "2",
    isPrimary: false,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-media-townhouse-1",
    propertyId: "demo-garden-townhouse",
    type: "photo",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    altText: "Garden Townhouse exterior",
    caption: "Private residential entry",
    sortOrder: "1",
    isPrimary: true,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-media-studio-1",
    propertyId: "demo-sunlit-studio",
    type: "photo",
    url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    altText: "Sunlit Studio living and sleeping area",
    caption: "Efficient open studio plan",
    sortOrder: "1",
    isPrimary: true,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  }
];

export const defaultFaqs: FaqRecord[] = [
  {
    id: "demo-faq-availability",
    question: "Is this property still available?",
    answer: "Availability can change quickly. Use the inquiry form and the agency will confirm the current status before scheduling.",
    keywords: "available|availability|still available|vacant",
    active: true,
    sortOrder: "1",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-faq-viewing",
    question: "How can I schedule a viewing?",
    answer: "Send an inquiry with your preferred contact method and move-in timeline. The agency will follow up with viewing options.",
    keywords: "viewing|tour|schedule|appointment|visit",
    active: true,
    sortOrder: "2",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-faq-application",
    question: "What do I need to apply?",
    answer: "Typical applications ask for contact details, identity verification, income or employment information, and references. Requirements can vary by property.",
    keywords: "apply|application|requirements|documents",
    active: true,
    sortOrder: "3",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-faq-location",
    question: "Can I see the location?",
    answer: "Open the Google Maps link on the property page when one is available. Contact the agency if you need exact arrival details.",
    keywords: "location|map|maps|address|directions",
    active: true,
    sortOrder: "4",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  },
  {
    id: "demo-faq-contact",
    question: "How do I contact the agency?",
    answer: "Use the property inquiry form with your email or phone number. The agency will respond using your preferred contact method.",
    keywords: "contact|email|phone|call|message",
    active: true,
    sortOrder: "5",
    createdBy: demoActor,
    updatedBy: demoActor,
    createdAt: demoTimestamp,
    updatedAt: demoTimestamp
  }
];
